/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ups.edu.ec.vista;

import javax.swing.JMenuItem;
import ups.edu.ec.controlador.ControladorAlumno;
import ups.edu.ec.controlador.ControladorCurso;
import ups.edu.ec.controlador.ControladorDocente;
import ups.edu.ec.controlador.ControladorRector;

/**
 *
 * @author user
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private ControladorCurso controladorCurso;
    private ControladorAlumno controladorAlumno;
    private ControladorDocente controladorDocente;
    private ControladorRector controladorRector;
    private VentanaCrearDocente ventanaCrearDocente;
    private VentanaCrearRector ventanaCrearRector;
    private VentanaLoginDocente ventanaLoginDocente;
    private VentanaLoginRector ventanaLoginRector;
    private VentaRectorado ventaRectorado;
    private VentanaDocentesAsignados ventanaDocentesAsignados;
    

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        controladorCurso= new ControladorCurso();
        controladorRector = new ControladorRector();
        controladorAlumno=new ControladorAlumno();
        controladorDocente = new ControladorDocente();
        ventanaCrearDocente = new VentanaCrearDocente(controladorDocente);
        ventanaCrearRector = new VentanaCrearRector(controladorRector);
        ventanaLoginDocente = new VentanaLoginDocente(controladorDocente,this);
        ventanaLoginRector = new VentanaLoginRector(controladorRector,this);
        ventaRectorado=new VentaRectorado(controladorDocente,controladorCurso);
        ventanaDocentesAsignados=new VentanaDocentesAsignados(controladorAlumno,controladorDocente,controladorCurso);
        jMenuItemGestionar.setVisible(false);
        jMenuItemGestonarD.setVisible(false);
     
         

    }

    public JMenuItem getjMenuItemGestionar() {
        return jMenuItemGestionar;
    }

    public void setjMenuItemGestionar(JMenuItem jMenuItemGestionar) {
        this.jMenuItemGestionar = jMenuItemGestionar;
    }

    public JMenuItem getjMenuItemGestonarD() {
        return jMenuItemGestonarD;
    }

    public void setjMenuItemGestonarD(JMenuItem jMenuItemGestonarD) {
        this.jMenuItemGestonarD = jMenuItemGestonarD;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRector = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemGestionar = new javax.swing.JMenuItem();
        jMenuItemCrear = new javax.swing.JMenuItem();
        jMenuDocente = new javax.swing.JMenu();
        jMenuItemLoginD = new javax.swing.JMenuItem();
        jMenuItemGestonarD = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        jMenuRector.setText("Rector");

        jMenuItemLogin.setText("Iniciar Sesion");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenuRector.add(jMenuItemLogin);

        jMenuItemGestionar.setText("Gestionar");
        jMenuItemGestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionarActionPerformed(evt);
            }
        });
        jMenuRector.add(jMenuItemGestionar);

        jMenuItemCrear.setText("Crear");
        jMenuItemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearActionPerformed(evt);
            }
        });
        jMenuRector.add(jMenuItemCrear);

        jMenuBar1.add(jMenuRector);

        jMenuDocente.setText("Docente");

        jMenuItemLoginD.setText("IniciarSesion");
        jMenuItemLoginD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginDActionPerformed(evt);
            }
        });
        jMenuDocente.add(jMenuItemLoginD);

        jMenuItemGestonarD.setText("Gestionar");
        jMenuItemGestonarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestonarDActionPerformed(evt);
            }
        });
        jMenuDocente.add(jMenuItemGestonarD);

        jMenuBar1.add(jMenuDocente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearActionPerformed
        desktopPane.add(ventanaCrearRector);
        ventanaCrearRector.setVisible(true);
    }//GEN-LAST:event_jMenuItemCrearActionPerformed

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        desktopPane.add(ventanaLoginRector);
        ventanaLoginRector.setVisible(true);
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItemLoginDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginDActionPerformed
        desktopPane.add(ventanaLoginDocente);
        ventanaLoginDocente.setVisible(true);
    }//GEN-LAST:event_jMenuItemLoginDActionPerformed

    private void jMenuItemGestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionarActionPerformed
      jMenuItemGestionar.setVisible(false);
      desktopPane.add(ventaRectorado);
      ventaRectorado.setVisible(true);
    }//GEN-LAST:event_jMenuItemGestionarActionPerformed

    private void jMenuItemGestonarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestonarDActionPerformed
      jMenuItemGestonarD.setVisible(false);
      desktopPane.add(ventanaDocentesAsignados);
      ventanaDocentesAsignados.setVisible(true);
    }//GEN-LAST:event_jMenuItemGestonarDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDocente;
    private javax.swing.JMenuItem jMenuItemCrear;
    private javax.swing.JMenuItem jMenuItemGestionar;
    private javax.swing.JMenuItem jMenuItemGestonarD;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemLoginD;
    private javax.swing.JMenu jMenuRector;
    // End of variables declaration//GEN-END:variables
}
